---
servers:
  -
    enabled: true
    hostname: brs.2.2.0.dev.wso2.org
    facters:
      product_name: wso2mb
      product_version: 3.0.0
      product_profile: default
      environment: dev
    box: ubuntu/trusty64
    ip: 192.168.100.2
    ram: 2048
    cpu: 1
  -
    enabled: false
    hostname: is.5.0.0.dev.wso2.org
    facters:
      product_name: wso2is
      product_version: 5.0.0
      product_profile: default
      environment: dev
    box: ubuntu/trusty64
    ip: 192.168.100.3
    ram: 2048
    cpu: 1
  -
    enabled: false
    hostname: am.1.9.1.dev.wso2.org
    facters:
      product_name: wso2am
      product_version: 1.9.1
      product_profile: default
      environment: dev
    box: ubuntu/trusty64
    ip: 192.168.100.4
    ram: 2048
    cpu: 1
puppet:
    puppet_home: /etc/puppet
