# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wso2::hostname: wso2am-gateway-manager
wso2::mgt_hostname: wso2am-gateway-manager

wso2::apim_keymanager:
    host: wso2am-api-key-manager

wso2::clustering:
    enabled: true
    membership_scheme: kubernetes
    kubernetes:
       kubernetes_master: http://172.17.8.101:8080
       kubernetes_namespace: default
       kubernetes_services: wso2am-gateway-manager
       #kubernetes_master_username:
       #kubernetes_master_password:

wso2::file_list:
  - repository/components/lib/jackson-annotations-2.5.4.jar
  - repository/components/lib/jackson-core-2.5.4.jar
  - repository/components/lib/jackson-databind-2.5.4.jar
  - repository/components/lib/kubernetes-membership-scheme-1.0.0-SNAPSHOT.jar
  - repository/components/lib/mysql-connector-java-5.1.36-bin.jar

wso2::ports:
  proxyPort:
    http: 32007
    https: 32008

wso2::master_datasources:
  wso2_gov_db:
    name: WSO2_GOV_DB
    description: The datasource used for gov registry
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.8.1:3306/GOV_DB?autoReconnect=true
    username: root
    password: root
    jndi_config: jdbc/WSO2_GOV_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_config_db:
    name: WSO2_CONFIG_DB
    description: The datasource used for config registry
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.8.1:3306/GW_CONFIG_DB?autoReconnect=true
    username: root
    password: root
    jndi_config: jdbc/WSO2_CONFIG_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::am_datasources:
  wso2am_db:
    name: WSO2AM_DB
    description: The datasource used for API Manager database
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.8.1:3306/APIMGT_DB?autoReconnect=true
    username: root
    password: root
    jndi_config: jdbc/WSO2AM_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::registry_mounts:
  wso2_config_db:
    path: /_system/config
    target_path: /_system/config
    read_only: false
    registry_root: /
    enable_cache: true
  wso2_gov_db:
    path: /_system/governance
    target_path: /_system/governance
    read_only: false
    registry_root: /
    enable_cache: true

wso2::usermgt_datasource: wso2_carbon_db
