# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
classes:
  - wso2cep
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"

wso2::template_list :
  - repository/conf/cep/storm/storm.yaml
  - repository/conf/event-processor.xml
  - repository/conf/data-bridge/data-agent-config.xml
  - repository/conf/data-bridge/data-bridge-config.xml
#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/cipher-tool.properties
#  - bin/ciphertool.sh
#  - password-tmp

wso2::service_name: wso2cep
wso2::hostname : wso2cep-default
wso2::mgt_hostname : wso2cep-default

wso2::file_list :
  - repository/components/lib/jackson-annotations-2.5.4.jar
  - repository/components/lib/jackson-core-2.5.4.jar
  - repository/components/lib/jackson-databind-2.5.4.jar
  - repository/components/lib/kubernetes-membership-scheme-1.0.0-SNAPSHOT.jar
  - repository/components/lib/mysql-connector-java-5.1.36-bin.jar

wso2::registry_mounts:
  wso2_config_db:
    name: WSO2_CONFIG_DB
    path: /_system/config/cep
    target_path: /_system/config
    read_only: false
    registry_root: /
    enable_cache: true

  wso2_gov_db:
    name: WSO2_GOV_DB
    path: /_system/gov
    target_path: /_system/gov
    read_only: false
    registry_root: /
    enable_cache: true

wso2::usermgt_datasource: wso2user_db
wso2::reg_datasource: wso2_config_db

wso2::master_datasources :
  wso2_config_db :
    name : WSO2_CONFIG_DB
    description : The datasource used for config registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://mysql-cepdb:3306/WSO2_CEP_DB?autoReconnect=true
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config : jdbc/WSO2_CONFIG_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2_gov_db :
    name : WSO2_GOV_DB
    description : The datasource used for gov registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://mysql-govdb:3306/WSO2_GOV_DB?autoReconnect=true
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config : jdbc/WSO2_GOV_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

  wso2user_db :
    name : WSO2USER_DB
    description : The datasource is used for user mangement and userstore
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://mysql-userdb:3306/WSO2_USER_DB?autoReconnect=true
    username: "%{hiera('wso2::datasources::common::username')}"
    password: "%{hiera('wso2::datasources::common::password')}"
    jndi_config : jdbc/WSO2USER_DB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::thrift_data_agent :
 queueSize : 100
 batchSize : 100
 corePoolSize : 100
 maxPoolSize : 100

wso2::binary_data_agent :
 queueSize : 200
 batchSize : 200
 corePoolSize : 200
 maxPoolSize : 200

wso2::data_bridge :
 workerThreads : 2
 maxEventBufferCapacity : 2
 eventBufferSize : 2
 clientTimeoutMin : 20

wso2::single_node_deployment :
 enabled : true

wso2::ha_deployment :
 enabled : false

wso2::distributed_deployment :
 enabled : false

# Secure vault configuration
wso2::enable_secure_vault : false
wso2::secure_vault_configs :
  key_store_password :
    secret_alias: Carbon.Security.KeyStore.Password
    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/Password,false
    password: wso2carbon
  key_store_key_password :
    secret_alias: Carbon.Security.KeyStore.KeyPassword
    secret_alias_value: repository/conf/carbon.xml//Server/Security/KeyStore/KeyPassword,false
    password: wso2carbon
  trust_store_password :
    secret_alias: Carbon.Security.TrustStore.Password
    secret_alias_value: repository/conf/carbon.xml//Server/Security/TrustStore/Password,false
    password: wso2carbon
  user_manager_admin_password :
    secret_alias: UserManager.AdminUser.Password
    secret_alias_value: repository/conf/user-mgt.xml//UserManager/Realm/Configuration/AdminUser/Password,false
    password: admin
  wso2_carbon_db_password :
    secret_alias: Datasources.WSO2_CARBON_DB.Configuration.Password
    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CARBON_DB']/definition[@type='RDBMS']/configuration/password,false
    password: wso2carbon
  connector_key_store_password :
    secret_alias: Server.Service.Connector.keystorePass
    secret_alias_value: repository/conf/tomcat/catalina-server.xml//Server/Service/Connector[@keystorePass],true
    password: wso2carbon
  adapter_output_mail_password:
    secret_alias: Adapter.Output.Mail.Password
    secret_alias_value: repository/conf/output-event-adapters.xml//adapterConfig[@type='email']/property[@key='mail.smtp.password'],false
    password: wso2carbon
#  dep_sync_svn_password :
#    secret_alias: Carbon.DeploymentSynchronizer.SvnPassword
#    secret_alias_value: repository/conf/carbon.xml//Sever/DeploymentSynchronizer/SvnPassword,false
#    password: password
#  wso2_config_db_password :
#    secret_alias: Datasources.WSO2_CONFIG_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CONFIG_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  wso2_gov_db_password :
#    secret_alias: Datasources.WSO2_GOV_DB.Configuration.Password
#    secret_alias_value: repository/conf/datasources/master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_GOV_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  user_store_manager_connection_password:
#    secret_alias: UserStoreManager.Property.ConnectionPassword
#    secret_alias_value: repository/conf/user-mgt.xml//UserManager/Realm/UserStoreManager/Property[@name='ConnectionPassword'],true
#    password: admin
#  user_store_manager_password:
#    secret_alias: UserStoreManager.Property.password
#    secret_alias_value: repository/conf/user-mgt.xml//UserManager/Realm/UserStoreManager/Property[@name='password'],true
#    password: admin
#  user_trusted_RPStore_password:
#    secret_alias: Security.UserTrustedRPStore.Password
#    secret_alias_value: repository/conf/identity.xml//Server/Security/UserTrustedRPStore/Password
#    password: wso2carbon
#  user_trusted_RPStore_key_password:
#    secret_alias: Security.UserTrustedRPStore.KeyPassword
#    secret_alias_value: repository/conf/identity.xml//Server/Security/UserTrustedRPStore/KeyPassword
#    password: wso2carbon
#  identity_system_store_pass:
#    secret_alias: Identity.System.StorePass
#    secret_alias_value: repository/conf/identity.xml//Server/Identity/System/StorePass
#    password: wso2carbon
#  xmpp_password:
#    secret_alias: MultifactorAuthentication.XMPPSettings.XMPPConfig.XMPPPassword
#    secret_alias_value: repository/conf/identity.xml//MultifactorAuthentication/XMPPSettings/XMPPConfig/XMPPPassword
#    password: wso2carbon
#  axis2_https_listener_trust_store_password:
#    secret_alias: Axis2.Https.Listener.TrustStore.Password
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='truststore']/TrustStore/Password,false
#    password: wso2carbon
#  axis2_https_listener_key_store_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.Password
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='keystore']/KeyStore/Password,false
#    password: wso2carbon
#  axis2_https_listener_key_store_key_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.KeyPassword
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='keystore']/KeyStore/KeyPassword,false
#    password: wso2carbon
#  axis2_https_sender_trust_store_password:
#    secret_alias: Axis2.Https.Listener.TrustStore.Password
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='truststore']/TrustStore/Password,false
#    password: wso2carbon
#  axis2_https_sender_key_store_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.Password
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='keystore']/KeyStore/Password,false
#    password: wso2carbon
#  axis2_https_sender_key_store_key_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.KeyPassword
#    secret_alias_value: repository/conf/axis2/axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='keystore']/KeyStore/KeyPassword,false
#    password: wso2carbon
#  axis2_mailto_parameter_password:
#    secret_alias: Axis2.Mailto.Parameter.Password
#    secret_alias_value: repository/conf/axis2.xml//axisconfig/transportSender[@name='mailto']/parameter[@name='mail.smtp.password'],false
#    password: wso2carbon

# for K8s scenario, need to enable proxy port to match NodePorts
# defined for servlet HTTP and HTTPS transport in K8s Service definition
wso2::ports:
  proxyPort :
    http: 32053
    https: 32054
